
# Configuration file for the "readthedocs" documentation build environment.

version: 2

sphinx:
  builder: html
  configuration: documentation/source/conf.py

# This is needed for numpy:
python:
  system.packages: true
